FROM node:20-alpine
WORKDIR /app
ENV VITE_API_URL=http://backend:8000/api
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build
EXPOSE 5173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]
